@HoneyDoApi_HostAddress = http://localhost:5007

GET {{HoneyDoApi_HostAddress}}/reminders/
Accept: application/json

###

GET {{HoneyDoApi_HostAddress}}/reminders/1
Accept: application/json

###
POST {{HoneyDoApi_HostAddress}}/reminders/create-reminder
Content-Type: application/json

{
"Title": "new reminder again",
  "Description": "new description",
  "Complete": true
}