@HoneyDoApi_HostAddress = http://localhost:5007

GET {{HoneyDoApi_HostAddress}}/reminders/
Accept: application/json

###

GET {{HoneyDoApi_HostAddress}}/reminders/get-reminder-by-id/?reminderId=675ba9b90644ac25f2a7f480
Accept: application/json

###
POST {{HoneyDoApi_HostAddress}}/reminders/create-reminder
Content-Type: application/json

{
"Title": "new reminder again",
  "Description": "new description",
  "Complete": true
}

###
POST {{HoneyDoApi_HostAddress}}/reminders/update-reminder
Content-Type: application/json

{
  "Id": "675ba9b90644ac25f2a7f480",
  "Title": "newer reminder",
  "Description": "updated description",
  "Complete": false
}